targets:
  - github
  - name: npm
    access: public
  - name: brew
    tap: getsentry/tools
    template: >
      class SentryCli < Formula
        desc "This is a Sentry command-line client for some generic tasks."
        homepage "https://github.com/getsentry/sentry-cli"
        url "https://github.com/getsentry/sentry-cli/releases/download/${ref}/sentry-cli-Darwin-x86_64"
        version "${ref}"
        sha256 "${checksums['sentry-cli-Darwin-x86_64']}"

        def install
          mv "sentry-cli-Darwin-x86_64", "sentry-cli"
          bin.install "sentry-cli"
        end

        test do
          assert_match version.to_s, shell_output("#{bin}/sentry-cli --version").chomp
        end
      end
