---
minVersion: '0.6.0'
github:
  owner: getsentry
  repo: sentry-cli
changelogPolicy: simple
targets:
  - name: gcs
    bucket: sentry-sdk-assets
    includeNames: /^sentry-cli-(Darwin|Windows|Linux).*$/i
    paths:
      - path: /sentry-cli/{{version}}/
        metadata:
          cacheControl: 'public, max-age=2592000'
      - path: /sentry-cli/latest/
        metadata:
          cacheControl: 'public, max-age=600'
  - name: npm
  - name: brew
    tap: getsentry/tools
    template: >
      class SentryCli < Formula
        desc "This is a Sentry command-line client for some generic tasks."
        homepage "https://github.com/getsentry/sentry-cli"
        url "https://downloads.sentry-cdn.com/sentry-cli/{{version}}/sentry-cli-Darwin-x86_64"
        version "{{version}}"
        sha256 "{{checksums.sentry-cli-Darwin-x86_64}}"

        def install
          mv "sentry-cli-Darwin-x86_64", "sentry-cli"
          bin.install "sentry-cli"
        end

        test do
          assert_match version.to_s, shell_output("#{bin}/sentry-cli --version").chomp
        end
      end
  - name: github
    includeNames: /^sentry-cli-(Darwin|Windows|Linux).*$/i
  - name: registry
    type: app
    urlTemplate: "https://downloads.sentry-cdn.com/sentry-cli/{{version}}/{{file}}"
    includeNames: /^sentry-cli-(Darwin|Windows|Linux).*$/i
    config:
      canonical: "app:sentry-cli"
