---
minVersion: '0.5.1'
github:
  owner: getsentry
  repo: sentry-cli
changelogPolicy: simple
targets:
  - name: npm
  - name: brew
    tap: getsentry/tools
    template: >
      class SentryCli < Formula
        desc "This is a Sentry command-line client for some generic tasks."
        homepage "https://github.com/getsentry/sentry-cli"
        url "https://github.com/getsentry/sentry-cli/releases/download/{{version}}/sentry-cli-Darwin-x86_64"
        version "{{version}}"
        sha256 "{{checksums.sentry-cli-Darwin-x86_64}}"

        def install
          mv "sentry-cli-Darwin-x86_64", "sentry-cli"
          bin.install "sentry-cli"
        end

        test do
          assert_match version.to_s, shell_output("#{bin}/sentry-cli --version").chomp
        end
      end
  - name: github
  - name: gcs
    bucket: sentry-sdk-assets
    paths:
      - path: /sentry-cli/{{version}}/
        maxCacheAge: 2592000
      - path: /sentry-cli/latest/
        maxCacheAge: 600
  - name: registry
    type: app
    urlTemplate: "https://downloads.sentry-cdn.com/sentry-cli/{{version}}/{{file}}"
    includeNames: /^.*sentry-cli.*$/
    config:
      canonical: "app:sentry-cli"
