---
minVersion: '0.14.0'
github:
  owner: getsentry
  repo: sentry-cli
changelogPolicy: simple

statusProvider:
  name: github
artifactProvider:
  name: github

targets:
  - name: gcs
    bucket: sentry-sdk-assets
    includeNames: /^sentry-cli-(Darwin|Windows|Linux).*$/i
    paths:
      - path: /sentry-cli/{{version}}/
        metadata:
          cacheControl: 'public, max-age=2592000'
      - path: /sentry-cli/latest/
        metadata:
          cacheControl: 'public, max-age=600'
  - name: npm
  - name: brew
    tap: getsentry/tools
    template: >
      class SentryCli < Formula
        desc "Sentry command-line client for some generic tasks"
        homepage "https://github.com/getsentry/sentry-cli"
        version "{{version}}"
        license "BSD-3-Clause"

        if OS.mac?
          url "https://downloads.sentry-cdn.com/sentry-cli/{{version}}/sentry-cli-Darwin-universal"
          sha256 "{{checksums.sentry-cli-Darwin-universal}}"
        elsif Hardware::CPU.is_64_bit?
          url "https://downloads.sentry-cdn.com/sentry-cli/{{version}}/sentry-cli-Linux-x86_64"
          sha256 "{{checksums.sentry-cli-Linux-x86_64}}"
        else
          url "https://downloads.sentry-cdn.com/sentry-cli/{{version}}/sentry-cli-Linux-i686"
          sha256 "{{checksums.sentry-cli-Linux-i686}}"
        end

        def install
          bin.install Dir["sentry-cli-*"].first => "sentry-cli"
        end

        test do
          assert_match version.to_s, shell_output("#{bin}/sentry-cli --version").chomp
        end
      end
  - name: github
    includeNames: /^sentry-cli-(Darwin|Windows|Linux).*$/i
  - name: registry
    type: app
    urlTemplate: "https://downloads.sentry-cdn.com/sentry-cli/{{version}}/{{file}}"
    includeNames: /^sentry-cli-(Darwin|Windows|Linux).*$/i
    checksums:
      - algorithm: sha256
        format: hex
    config:
      canonical: "app:sentry-cli"

requireNames:
  - /^sentry-cli-Darwin-x86_64$/
  - /^sentry-cli-Darwin-arm64$/
  - /^sentry-cli-Darwin-universal$/
  - /^sentry-cli-Linux-i686$/
  - /^sentry-cli-Linux-x86_64$/
  - /^sentry-cli-Windows-i686.exe$/
  - /^sentry-cli-Windows-x86_64.exe$/
