name: Release GHCR Versioned Image

on:
  release:
    types: [prereleased, released]

jobs:
  release-ghcr-version-tag:
    runs-on: ubuntu-24.04
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # 4.1.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag release version
        env:
          REF_NAME: ${{ github.ref_name }}
          SHA: ${{ github.sha }}
        run: |
          docker buildx imagetools create \
            -t ghcr.io/getsentry/sentry-cli:"$REF_NAME" \
            ghcr.io/getsentry/sentry-cli:"$SHA"
