name: Test Swift

on:
  workflow_call:
    outputs:
      matrix-result:
        description: 'Job result'
        value: ${{ jobs.run-tests.result }}

jobs:
  run-tests:
    name: Run tests
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # 6.0.3
      - name: Run tests
        working-directory: apple-catalog-parsing/native/swift/AssetCatalogParser
        run: swift test
