name: Test PR Head SHA Detection

on:
  pull_request:
    paths:
      - 'src/utils/vcs.rs'
      - '.github/workflows/test-pr-head-sha.yml'

jobs:
  test-head-sha-detection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        run: |
          rustup set profile minimal
          rustup component add clippy rustfmt

      - name: Build sentry-cli
        run: |
          echo "=== Building sentry-cli ==="
          cargo build --release
          echo "✅ Built sentry-cli at: target/release/sentry-cli"

      - name: Show GitHub Actions Environment
        run: |
          echo "=== GitHub Actions Environment ==="
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "GITHUB_SHA (merge commit): ${{ github.sha }}"
          echo "GITHUB_HEAD_REF: ${{ github.head_ref }}"
          echo "GITHUB_BASE_REF: ${{ github.base_ref }}"
          echo "PR Head SHA (actual commit): ${{ github.event.pull_request.head.sha }}"
          echo "PR Base SHA: ${{ github.event.pull_request.base.sha }}"
          echo "GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"

          if [ -f "$GITHUB_EVENT_PATH" ]; then
            echo ""
            echo "=== GitHub Event Payload Preview ==="
            echo "Event file exists at: $GITHUB_EVENT_PATH"
            echo "Looking for pull_request.head.sha in payload:"
            grep -A 5 -B 2 '"head"' "$GITHUB_EVENT_PATH" | head -15 || echo "No head section found"
          else
            echo "No event file found at $GITHUB_EVENT_PATH"
          fi

      - name: Test Built CLI Head SHA Detection
        run: |
          echo "=== Testing Real sentry-cli Head SHA Detection ==="
          echo ""

          # Show what git thinks HEAD is (this will be the merge commit)
          echo "Git HEAD (merge commit): $(git rev-parse HEAD)"
          echo "PR Head SHA (from event): ${{ github.event.pull_request.head.sha }}"
          echo ""

          if [ "$(git rev-parse HEAD)" != "${{ github.event.pull_request.head.sha }}" ]; then
            echo "✅ PERFECT TEST SCENARIO: Git HEAD differs from PR head SHA!"
            echo "   This is exactly the problem our fix solves."
            echo ""
          else
            echo "ℹ️  Git HEAD matches PR head SHA (unusual scenario)"
            echo ""
          fi

          # Use the real APK file that should already be in the repo
          ls -la test_artifacts/ || echo "No test_artifacts directory found"

          echo "=== Running sentry-cli build upload with debug logging ==="
          echo "Command: ./target/release/sentry-cli --log-level debug build upload test_artifacts/app-debug.apk"
          echo ""
          echo "🔍 WATCH FOR DEBUG LOGS BELOW:"
          echo "Expected debug log: 'Using GitHub Actions PR head SHA from event payload: ${{ github.event.pull_request.head.sha }}'"
          echo ""
          echo "--- CLI OUTPUT START ---"

          # Test the CLI's head-sha detection with debug logging enabled
          # Using a dummy auth token to get past auth check and reach the head-sha detection logic
          ./target/release/sentry-cli --log-level debug --auth-token dummy_token_for_testing build upload test_artifacts/app-debug.apk || true

          echo "--- CLI OUTPUT END ---"

          echo ""
          echo "=== Analysis ==="
          echo "Expected behavior:"
          echo "  - CLI should detect GITHUB_EVENT_PATH environment variable"
          echo "  - CLI should extract PR head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "  - CLI should use that instead of git HEAD: $(git rev-parse HEAD)"

      - name: Test CLI Without GitHub Context (Fallback Behavior)
        run: |
          echo "=== Testing Fallback Behavior (No GitHub Actions Context) ==="

          # Unset GitHub environment variables to test fallback
          unset GITHUB_EVENT_PATH
          unset GITHUB_EVENT_NAME

          echo "Running CLI without GitHub Actions context (with debug logging)..."
          ./target/release/sentry-cli --log-level debug --auth-token dummy_token_for_testing build upload test_artifacts/app-debug.apk || true

          echo ""
          echo "Expected: Should fall back to 'git rev-parse HEAD'"

      - name: Verify Our Fix Logic
        run: |
          echo "=== Verification Summary ==="
          echo ""
          echo "🎯 Test Results:"
          echo "1. Git HEAD (merge commit):     $(git rev-parse HEAD)"
          echo "2. PR Head SHA (real commit):   ${{ github.event.pull_request.head.sha }}"
          echo "3. GitHub Event Path exists:    $([ -f "$GITHUB_EVENT_PATH" ] && echo "✅ YES" || echo "❌ NO")"
          echo ""

          if [ "$(git rev-parse HEAD)" != "${{ github.event.pull_request.head.sha }}" ]; then
            echo "✅ SUCCESS: This PR demonstrates the exact problem our fix solves!"
            echo ""
            echo "Without our fix: sentry-cli would use $(git rev-parse HEAD)"
            echo "With our fix:    sentry-cli should use ${{ github.event.pull_request.head.sha }}"
            echo ""
            echo "The fix detects GitHub Actions PR context and extracts the real commit SHA"
            echo "from the event payload instead of using the temporary merge commit."
          else
            echo "ℹ️  In this case, git HEAD happens to match the PR head SHA"
            echo "   But our fix still works correctly for the general case."
          fi